### ISSUE TITLE
Zoe Apply Writing Checklist

### ISSUE THREAD

**Issue by katyhuff** [ZoeRichter/master-thesis#12]
Hi @ZoeRichter. Although we're lucky to have undergrads working to ensure the clarity of your writing, it is also the responsibility of the author to write and iterate on drafts in accordance with the writing checklist. Please take a pass through all of the checklist items before submitting your final version to @munkm and I. Don't forget the other resources available to you at https://arfc.github.io/manual/guides/writing/ and https://arfc.github.io/manual/guides/writing/ms-thesis .

## General
- [x] Run a spell checker.
- [x] The Oxford comma must appear in lists ("lions, tigers, and bears.")
- [x] Do not use the word "where" unless referring to a location (try "such that" or "in which").
- [x] Do not use the word "when" unless referring to a time (try "if" instead).
- [x] Only use "large" when referring to size.
- [x] Use of "very" suggests that a cooler word exists.
- [x] Other misused/overused words include: code, input, output, different, value, amount, model.
- [x] Articles such as "a" "the" "some" "any" and "each" must appear where necessary.
- [x] All subjects match the plurality of their verbs ( no: "Apples is tasty" yes: "Apples are tasty")
- [x] Avoid run-on sentences.
- [x] clunky nouns -> spunky verbs (progression, expression --> progress, express)
- [x] reduce vague words (important, methodologic)
- [x] reduce acronyms / jargon
- [x] expand all acronyms on first use (rely on the acros.tex file and glossaries package to automate this)
- [x] get rid of unnecessary prepositional phrases -- author clearing throat (It can be shown that)
- [x] #13
- [x] get rid of there are / there is
- [x] turn negatives to positives (she was not often right -> she was usually wrong)
- [x] get rid of extraneous prepositions (the meeting happened on monday -> the meeting happened monday) (they agreed that it was true -> they agreed it was true)
- [x] get rid of passive voice (is/was/are/were/be/been/am + past tense verb), replace with active voice
- [x] use strong verbs (use sparingly: is, are, was, were, be, been, am)
- [x] avoid turning verbs into nouns ("obtain estimates of" -> "estimates"; "provides a description of" -> "describes")
- [x] don't bury the verb (keep the predicate close to the subject at the beginning of the sentence)
- [x] data is plural (the data are critical)
- [x] compare to (point out similarities between different things) vs.  compared with (point out differences between similar things)
- [x] punctuation helps you to vary your sentence structure
- [x] Power to separate in increasing power: comma, colon, dash, parentheses, semicolon, period
- [x] In increasing order of formality: dash, parentheses, all of the others. Don't overdo it with the dash and parentheses
- [x] semicolon: connects two independent clauses. OR used to separate when the items in the list contain internal punctuation.
- [x] use a colon to introduce a list, quote, explanation, conclusion, or amplification
- [x] if there's a list in a sentence, it shouldn't come before the colon
- [x] use a dash to insert something in the middle of the sentence. Don't overuse it.
- [x] Always use isotopic notation like `$^{239}Pu$`. Never $Pu-239$ or plutonium-239.
- [x] Elemental symbols (Ni, Li, Na, Pu) are capitalized, but their names are not (nickel, lithium, sodium, plutonium).
- [x] A phrase of the form <verb>ion of <noun> is probably clearer as <noun> <verb>ion. (For example, convert "calculation of velocity" to "velocity calculation".)
- [x] Cite all images, methods, software, and empirical data. Review [the principles](https://www.force11.org/software-citation-principles) and try [CiteAs](https://citeas.org/about) if necessary.
- [x] Refer to software consistently by name.
- [x] Each sentence/paragraph should logically follow the previous sentence/paragraph.
- [x] Be concise and direct.
- [x] When giving examples, use variables instead of numbers and use symbolic math instead of acronyms.
- [x] When you introduce words or phrases that are unusual or likely to be unfamiliar to the reader, italicize them.
- [x] If you use an uncommon word, either consider changing it or define it in its first usage.
- [x] You're a human writing for other humans: Make the wording exciting, and remember some people reading it won't know as much jargon as you do.
- [x] Vary your sentence structure to keep readers engaged.

## Additional Table and Figure Checklist:

- [x] The text should refer to all tables and figures.
- [x] When referring to figures by their number, use `Figure 1` and `Table 1.` They should be capitalized and not abbreviated (not `fig. 1` or `figure 1`.)
- [x] In tables, align all columns of numbers such that the decimals line up.
- [x] In a single column, all values should probably have the same number of significant digits.
- [x] Give units for each numerical column.
- [x] A table should have only 3 horizontal lines (no vertical lines and no more than 3.)

## Additional Math Comments:

- [x] define all variables, with units. If unitless, indicate that this is the case `$[-]$`.
- [x] subscripts should be brief and can be avoided with common notation. For example, `$\dot{m}$` is better than `$m_f$` which is superior to `$m_{flow}$`.
- [x] variable names should be symbols rather than words `m` is better than `mass` and `\ksi` is better than `one_time_use_variable`.
- [x] The notation $3.0\times10^12$ is preferred over $3e12$.
- [x] Equations should be part of a sentence.
- [x] Equations should be in the `align` environment. Align them at the `=` sign.
- [x] Variables should be defined in the `align` environment as well, not buried in paragraphs.

## Here’s an example of an equation:

```latex
The line is defined as
\begin{align}
y&=mx + b
\intertext{where}
y&= \mbox{ height of the line, also known as rise [m]}\nonumber\\
m&= \mbox{ slope [-]}\nonumber\\
x&=\mbox{ independent parameter, known as run [m]}\nonumber\\
b&= \mbox{ y intercept [m].}
\end{align}
```

**Comment by katyhuff** [comment]
https://www.dropbox.com/s/m5wg5dqa3tcfclh/main.pdf?dl=0
